package com.fti.recyclerview;

import java.util.ArrayList;

public class BukuData {
    private static String[] title = new String[]{"1. A Study in Scarlet (A. Conan Doyle)", "2. The Hound of the Baskervilles (A. Conan Doyle)","3. The Murder of Roger Ackroyd (Agatha Christie)", "4. A is For Alibi (Sue Grafton)","5. Knots & Crosses (Ian Rankin)","6. The Poisoned Chocolate Cases ( Anthony Berkley)","7. The Big Sleep (Raymond Chandler)","8. The Moonstone (Wilkie Collins)", "9. The Maltese Falcon (Dashiell Hammett)", "10. And Then There Were None (Agatha Christie)"};
    private static int[] thumbnail = new int[]{R.drawable.buku1,R.drawable.buku2,R.drawable.buku3,R.drawable.buku4,R.drawable.buku5,R.drawable.buku6,R.drawable.buku7,R.drawable.buku8,R.drawable.buku9,R.drawable.buku10};
    private static String[] price = new String[]{"335.000","350.000","200.000","215.000","375.000","275.000","220.000","185.000","215.000", "210.000"};

    private static String[] desc = new String[]{
            "A Study in Scarlet mengisahkan cerita pembunuhan dan balas dendam yang diceritakan dari sudut pandang orang ketiga. Gaya ini merupakan yang pertama dalam cerita misteri. Yang menariknya, misteri itu dipecahkan sepenuhnya oleh penalaran deduktif dan kecerdasan dari sang detektif, sesuatu yang baru di era Victoria.",
            "The Hound of the Baskervilles yang ditulis tahun 1902 adalah yang paling terkenal dari novel-novel yang ditulis oleh Sir Arthur Conan Doyle. Novel ini ditulis selama periode sepuluh tahun saat Holmes dibunuh oleh Doyle sebelum akhirnya dibangkitkan lagi ketika dia bertemu Profesor Moriarty di Reichenbach Falls. Apakah anjing pemburu raksasa tersebut benar-benar meneror orang di Dartmoor?",
            "Novel ini dianggap sebagai salah satu novel terbaik dan kontroversial dari Agatha Christie. Tokoh utama dalam novel ini bernama Hercules Poirot. Poirot adalah seorang dokter yang hidup membujang hingga usia paruh baya. Dia tinggal bersama kakak perempuannya. Poirot seorang dokter desa yang gemar berkebun dan hidup bersahaja. Satu hari dia bertemu dan berkenan dengan tetangga baru bernama Roger Ackroyd yang bercerita bahwa dia baru saja mendapatkan warisan. Saat larut malam, Ackroyd tiba-tiba meninggal setelah dia beristirahat dan misteri pun dimulai. Yang menarik dari cerita ini adalah detail-detail yang diberikan Poirot pada tetangganya yang membuat pembaca  menebak pembunuh sebenarnya.",
            "Setting novel ini di Santa Barbara, California. Kisah detektif karya Sue Grafton 'A is for Alibi' memakai racun sebagai motifnya dan racun yang dipilih adalah bunga mentega atau oleander yang dihancurkan. Banyak usaha yang telah dilakukan oleh pembunuh untuk menyembunyikan kejahatan mereka, karena racun ini telah dibuat menjadi tablet dan disamarkan sebagai pil antihistamin yang tidak berbahaya. Penyelidik wanita bernama Kinsey Milhone adalah tokoh utama dari karya Sue Grafton dan pembaca bisa terlibat dalam penyelesaian kasus ketika dia berusaha menyelesaikan kejahatan keji ini. Grafton mengutip cerita pembunuhannya dari cerita tentang ex-suaminya setelah perceraian yang berantakan. Fakta yang sederhana, tapi mengerikan  membuat pembaca  terpikat sampai halaman terakhir.",
            "Novel detektif yang sangat mendalam ini tokohnya terdiri dari pengedar narkoba besar bernama Michael Rebus. Dia memiliki seorang saudara lelaki bernama John Rebus yang seorang polisi. Saudaranya sedang diselidiki oleh protagonis utama cerita ini yang bernama Jim Stevens, seorang jurnalis. Berlatar dunia kriminal di Edinburgh, Skotlandia, Stevens berusaha untuk mengetahui seberapa banyak John Rebus mengetahui tentang kegiatan kriminal yang dilakukan saudaranya dan pembunuhan dua gadis muda. Dalam novel yang memfokuskan pada cerita masa lalu juga masa sekarang tokoh utama, pembaca terus menebak sampai kata terakhir. Benar novel untik penggemar misteri pembunuhan.",
            "Setelah Mr Bendix menerima hadiah sekotak cokelat dari orang yang misterius, dia memutuskan untuk membawanya pulang cokelat tersebut untuk istrinya. Setelah mencicipi beberapa buah cokelat di dalamnya, Nyonya Bendix mendadak jatuh sakit dan sedihnya sampai meninggal. Scotland Yard berusaha mengeliti kejahatan ini selama lebih dari setahun, tetapi benar-benar tak ada hasil. Roger Sheringham, yang merupakan bagian dari kelompok penyelesai kejahatan amatir, masuk dalam kasus ini dan mencoba untuk mengetahui fakta. Tiap orang yang terlibat yang berjumlah 6 orang bekerja secara independen satu sama lain dengan menggunakan teknik yang berbeda. Ini adalah tour detektif yang membuat pembaca terpesona, karena keterampilan deduktif para detektif tersebut.",
            "Novel karya Raymond Chadler ini sudah diadaptasi menjadi film sebanyak dua kali di tahun 1946 dan 1978. Di tahun 1999, The Big Sleep masuk sebagai salah satu buku dalam “100 Books of the Century” dan menduduki posisi ke-96. Pada tahun 2005, novel ini kembali masuk dalam “List of 100 Best Novels” di majalah Time. The Big Sleep menceritakan tokoh detektif bernama Philip Marlowe. Novel ini terkenal karena tingkat kerumitannya juga karakter saling silang antara satu sama lain. Selain itu, rahasia cerita diungkap selama sepanjang cerita. Judulnya adalah kata halus untuk kematian. Pada halaman terakhir novel ini merujuk pada perenungan tentang Sleep the big sleep",
            "Menurut para sarjana bahasa, The Moonstone dianggap sebagai buku detektif pertama dalam bahasa Inggris. Novel ini merupakan karya epistolary yang berarti ditulis dalam bentuk dokumen berurutan, dalam novel ini dokumen yang digunakan adalah surat. Ini merupakan gaya penulisan yang lazim dalam literatur pertengahan abad kesembilan belas. Awalnya novel ini adalah serial dalam majalah Charles Dickens, All The Year Round. Ketika novel The Moonstone diterbitkan, genre novel ini disebut \"novel sensasi\". Sekarang orang-orang menyebut karya-karya ini sebagai novel misteri atau novel suspense. Dalam novel ini, moonstone adalah berlian besar. Novel ini menceritakan tentang seorang perempuan yang dapat warisan berupa berlian kemudian berlian itu dicuri darinya. Jadi, sepanjang novel ini, misteri berputar pada siapa yang mencuri berlian dan mengapa.",
            "The Maltese Falcon merupakan novel detektif yang terbit pada tahun 1930-an. Awalnya merupakan cerita serial pada majalah Black Mask yang dimulai dengan edisi September 1929. Cerita dalam novel ini dinarasikan dari sudut pandang orang ketiga eksternal. Tak ada deskripsi apa pun yang muncul dari pikiran atau perasaan tokoh internal, hanya apa yang mereka katakan, lakukan, dan apa yang terlihat. Karakter utama novel ini adalah Sam Spade, yang merupakan seorang detektif swasta di San Francisco. Dia bermitra dengan Miles Archer. Miss Wonderley mempekerjakan mereka untuk mengikuti jejak Floyd Thursby. Dia melarikan diri bersama saudara perempuannya. Archer mengambil tugas itu tapi dia ditemukan mati tertembak begitu juga Thursby sehingga Spade jadi tersangka. ",
            "Novel ini terjual hingga sekitar 100 juta kopi. And Then There Were None merupakan misteri tersendiri dan bukan bagian dari cerita seri. Dalam sebuah wawancara, Christie mengatakan bahwa And Then There Were None merupakan novel yang paling sulit untuk ditulis. Diceritakan sepuluh orang asing yang memiliki sedikit kesamaan terpikat dengan sebuah rumah besar di lepas pantai Devon milik U.N.Owen yang misterius. Ketika makan malam, diputarlah sebuah rekaman dan suara pembawa acara yang tak nampak itu menuduh tiap orang menyembunyikan rahasia tentang kesalahan mereka. Malam itu, Tony Marston, mantan pengemudi ditemukan terbunuh oleh sianida. "
    };

    public static ArrayList<BukuModel> getListData(){
        BukuModel bukuModel = null;
        ArrayList<BukuModel> list = new ArrayList<>();
        for(int i = 0; i < title.length; i++){
            bukuModel = new BukuModel();
            bukuModel.setGambarBuku(thumbnail[i]);
            bukuModel.setJudulBuku(title[i]);
            bukuModel.setHargaBuku(price[i]);
            bukuModel.setSinopsisBuku(desc[i]);
            list.add(bukuModel);
        }
        return list;
    }
}
